services:
  db:
    image: postgres:16-alpine
    container_name: task-manager-fastapi
    restart: 'always'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=task-manager-db
    ports:
      - '15432:15432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
